fc_install: Remove bashisms
Signed-off-by: Fini Jastrow <ulf.fini.jastrow@desy.de>

diff --git a/fc_install b/fc_install
--- a/fc_install
+++ b/fc_install
@@ -5,14 +5,14 @@
 #
 # Usage:
 #
-#   $ curl -s https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/fc_install -o fc_install
-#   $ chmod ugo+x fc_install
-#   $ ./fc_install --help
+#   $ curl -s https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/install.sh -o install.sh
+#   $ chmod ugo+x install.sh
+#   $ ./install.sh --help
 #
 # Developer notes:
 #
-#   $ shfmt -i 4 -w fc_install
-#   $ shellcheck fc_install
+#   $ shfmt -i 4 -w install.sh
+#   $ shellcheck install.sh
 #
 # [1] https://www.nerdfonts.com/
 # [2] https://github.com/ryanoasis/nerd-fonts/releases
@@ -25,6 +25,15 @@ scriptversion="1.0.0"
 # Nerd Fonts Version: 3.5.0
 
 # shellcheck enable=require-variable-braces
+
+# This script must run with bash 3
+# In fact it is checked against `checkbashisms` and no bashisms are
+# used, except (because the workarounds are too involved):
+# - Regexes
+# - FUNCNAME
+#
+# Note that some tools on MacOS behave differently or have unfamiliar options
+# and that also needs to be checked
 
 set -euo pipefail
 if shopt | grep -s inherit_errexit; then
@@ -66,14 +75,14 @@ else
     FONT_DIR="${FONT_DIR:-${sys_share_dir}/${font_subdir}/NerdFonts}"
 fi
 
-_REQUIREMENTS=("curl" "sed" "tar" "mktemp" "wc")
+_REQUIREMENTS="curl mktemp sed tar wc"
 _GH_RELEASE_DATA=
 _GH_ASSET_DATA=
 
 # command line interface
 # ----------------------
 
-cmd.help() {
+cmd_help() {
     cat <<EOF
 Usage: $(basename "$0") <cmd>
 
@@ -91,11 +100,11 @@ cmd:
   remove    : uninstall all Nerd Fonts
 
 required tools:
-  ${_REQUIREMENTS[*]}
+  ${_REQUIREMENTS}
 EOF
 }
 
-cmd.install.help() {
+cmd_install_help() {
     cat <<EOF
 Usage: $(basename "$0") install [<fontname>|all]
 
@@ -115,58 +124,58 @@ The target directory is determined to be
   ${FONT_DIR}
 EOF
 }
-cmd.install() {
+cmd_install() {
     local font_name="${1-}"
     local tmp_folder
     local font_list
     local font_list_size
 
-    font_list=$(nerd.font_list)
+    font_list=$(nerd_font_list)
     # shellcheck disable=SC2086 # We actually need word splitting of font_list here
-    font_list_size=$(sh.count ${font_list})
+    font_list_size=$(sh_count ${font_list})
 
     if [ "${font_name}" = "all" ]; then
-        msg.info "install all ${font_list_size} fonts"
-        msg.warn "installing all fonts will take its time / time for a coffee break"
+        msg_info "install all ${font_list_size} fonts"
+        msg_warn "installing all fonts will take its time / time for a coffee break"
     elif [ "${font_name}" = "" ]; then
         PS3="Enter a number: "
         select font_name in ${font_list} "all"; do
             # shellcheck disable=SC2086 # We actually need word splitting of font_list here in the else
             if [ "${font_name}" = "all" ]; then
-                msg.info "install all ${font_list_size} fonts"
-                msg.warn "installing all fonts will take its time / time for a coffee break"
+                msg_info "install all ${font_list_size} fonts"
+                msg_warn "installing all fonts will take its time / time for a coffee break"
                 break
-            elif sh.in_array "${font_name}" ${font_list}; then
+            elif sh_in_array "${font_name}" ${font_list}; then
                 font_list="${font_name}"
                 break
             else
-                msg.err "invalid choice."
+                msg_err "invalid choice."
             fi
         done
-        msg.debug "user selected font ${font_name}"
+        msg_debug "user selected font ${font_name}"
     else
         # shellcheck disable=SC2086 # We actually need word splitting of font_list here
-        sh.in_array "${font_name}" ${font_list} ||
-            sh.die.err 42 "font ${font_name} does not exists in release ${GH_RELEASE_TAG}"
+        sh_in_array "${font_name}" ${font_list} ||
+            sh_die_err 42 "font ${font_name} does not exists in release ${GH_RELEASE_TAG}"
         font_list="${font_name}"
     fi
 
-    msg.info "install fonts into folder: ${FONT_DIR}"
+    msg_info "install fonts into folder: ${FONT_DIR}"
     tmp_folder="$(mktemp -d)"
-    msg.debug "Workdir ${tmp_folder}"
-    pushd "${tmp_folder}" &>/dev/null || sh.die.err 42 "can't cd ${tmp_folder}"
+    msg_debug "Workdir ${tmp_folder}"
+    cd -- "${tmp_folder}" >/dev/null 2>&1 || sh_die_err 42 "can't cd ${tmp_folder}"
     for font in ${font_list}; do
-        nerd.install_font "${font}"
+        nerd_install_font "${font}"
     done
-    popd &>/dev/null
-    rm -rf "${tmp_folder}"
+    cd - >/dev/null 2>&1
+    rm -rf -- "${tmp_folder}"
     if command fc-cache; then
-        msg.info "fontconfig: build font information cache files"
+        msg_info "fontconfig: build font information cache files"
         fc-cache
     fi
 }
 
-cmd.remove.help() {
+cmd_remove_help() {
     cat <<EOF
 Usage: $(basename "$0") remove
 
@@ -175,33 +184,33 @@ In fact purging the directory ${FONT_DIR}
 EOF
 }
 
-cmd.remove() {
-    [ "$#" -ne 0 ] && sh.die.err 42 "${FUNCNAME#"cmd."}: unknown arguments $*"
+cmd_remove() {
+    [ "$#" -ne 0 ] && sh_die_err 42 "${FUNCNAME#"cmd."}: unknown arguments $*"
     if [ -d "${FONT_DIR}" ]; then
-        msg.info "remove font folder ${FONT_DIR}"
+        msg_info "remove font folder ${FONT_DIR}"
         rm -rf "${FONT_DIR}"
         if command fc-cache; then
-            msg.info "fontconfig: build font information cache files"
+            msg_info "fontconfig: build font information cache files"
             fc-cache
         fi
     else
-        msg.err "Nerd Fonts not installed at ${FONT_DIR}"
+        msg_err "Nerd Fonts not installed at ${FONT_DIR}"
     fi
 }
 
-cmd.list() {
-    [ "$#" -ne 0 ] && sh.die.err 42 "${FUNCNAME#"cmd."}: unknown arguments $*"
+cmd_list() {
+    [ "$#" -ne 0 ] && sh_die_err 42 "${FUNCNAME#"cmd."}: unknown arguments $*"
     if [ "${GH_RELEASE_TAG}" = "latest" ]; then
-        GH_RELEASE_TAG="$(gh.latest_release)"
-        msg.info "${GH_OWNER}/${GH_REPO}: latest (${GH_RELEASE_TAG})"
+        GH_RELEASE_TAG="$(gh_latest_release)"
+        msg_info "${GH_OWNER}/${GH_REPO}: latest (${GH_RELEASE_TAG})"
     else
-        msg.info "${GH_OWNER}/${GH_REPO}: ${GH_RELEASE_TAG}"
+        msg_info "${GH_OWNER}/${GH_REPO}: ${GH_RELEASE_TAG}"
     fi
-    nerd.font_list
+    nerd_font_list
 }
 
-cmd.env() {
-    [ "$#" -ne 0 ] && sh.die.err 42 "${FUNCNAME#"cmd."}: unknown arguments $*"
+cmd_env() {
+    [ "$#" -ne 0 ] && sh_die_err 42 "${FUNCNAME#"cmd."}: unknown arguments $*"
     cat <<EOF
 You can set these variables, and the current values are:
 VERBOSE=${VERBOSE}
@@ -226,7 +235,7 @@ EOF
 # Nerd Fonts
 # ----------
 
-nerd.assemble_released_archives() {
+nerd_assemble_released_archives() {
     # Returns pairs of "Archive-basename asset-ID"
     local archive_suffix=.tar.xz
     local assets_regex="^ *\"assets\":"
@@ -239,8 +248,8 @@ nerd.assemble_released_archives() {
     local assets_started=
     local aid=
     local name=
-    msg.debug "nerd.assemble_released_archives() for ${archive_suffix}"
-    gh.release_data |
+    msg_debug "nerd_assemble_released_archives() for ${archive_suffix}"
+    gh_release_data |
         while IFS= read -r line; do
             [ -z "${assets_started}" ] && [[ ! "${line}" =~ ${assets_regex} ]] && continue
             assets_started=true
@@ -262,13 +271,13 @@ nerd.assemble_released_archives() {
         done
 }
 
-nerd.released_archives() {
-    _GH_ASSET_DATA="${_GH_ASSET_DATA:-$(nerd.assemble_released_archives)}"
+nerd_released_archives() {
+    _GH_ASSET_DATA="${_GH_ASSET_DATA:-$(nerd_assemble_released_archives)}"
     printf "%s\n" "${_GH_ASSET_DATA}"
 }
 
-nerd.font_list() {
-    nerd.released_archives |
+nerd_font_list() {
+    nerd_released_archives |
         while IFS= read -r line; do
             if [[ "${line}" == *FontPatcher* ]]; then
                 continue
@@ -277,9 +286,9 @@ nerd.font_list() {
         done
 }
 
-nerd.find_asset_id() {
+nerd_find_asset_id() {
     local aid=
-    nerd.released_archives |
+    nerd_released_archives |
         while IFS= read -r line; do
             if [ "${line%%|*}" = "${1}" ]; then
                 echo "${line#*|}"
@@ -287,19 +296,19 @@ nerd.find_asset_id() {
         done
 }
 
-nerd.install_font() {
-    # usage:  nerd.install_font <font name>
+nerd_install_font() {
+    # usage:  nerd_install_font <font name>
 
     local aid
-    aid=$(nerd.find_asset_id "${1}")
+    aid=$(nerd_find_asset_id "${1}")
     if [ -z "${aid}" ]; then
-        sh.die.err 42 "Can not find asset ID of ${1}"
+        sh_die_err 42 "Can not find asset ID of ${1}"
     fi
-    msg.info "download & install font: ${1} (asset ${aid})"
+    msg_info "download & install font: ${1} (asset ${aid})"
     (
         set -e
         local dst
-        gh.download_asset "${1}.tar.xz" "${aid}"
+        gh_download_asset "${1}.tar.xz" "${aid}"
         mkdir -p "${1}"
         tar xf "${1}.tar.xz" -C "${1}"
         mkdir -p "${FONT_DIR}"
@@ -307,53 +316,53 @@ nerd.install_font() {
         for filename in "${1}"/*; do
             if [[ "${filename##*.}" =~ ${FONT_FORMATS} ]]; then
                 dst="${FONT_DIR}/$(basename "${filename}")"
-                msg.debug "install font: ${dst}"
+                msg_debug "install font: ${dst}"
                 mv "${filename}" "${dst}"
                 found_one=true
             fi
         done
         if [ -z "${found_one}" ]; then
-            msg.warn "no font file matching \"${FONT_FORMATS}\" for ${1}"
+            msg_warn "no font file matching \"${FONT_FORMATS}\" for ${1}"
         fi
     )
-    sh.prompt-err $?
+    sh_prompt_err $?
 }
 
 # github tools
 # ------------
 
-gh.latest_release() {
-    msg.debug "gh.latest_release() URL https://github.com/${GH_OWNER}/${GH_REPO}/releases/latest"
+gh_latest_release() {
+    msg_debug "gh_latest_release() URL https://github.com/${GH_OWNER}/${GH_REPO}/releases/latest"
     basename "$(curl -H "${AUTH}" -fs -o/dev/null -w "%{redirect_url}" "https://github.com/${GH_OWNER}/${GH_REPO}/releases/latest")"
 }
 
-gh.release_data() {
-    gh.release_tag
+gh_release_data() {
+    gh_release_tag
     if [ "${_GH_RELEASE_DATA}" = "" ]; then
-        _GH_RELEASE_DATA="$(gh.get_release_data)"
+        _GH_RELEASE_DATA="$(gh_get_release_data)"
     fi
-    if echo "${_GH_RELEASE_DATA}" | grep -q '"message": "Not Found"' &>/dev/null; then
-        msg.debug "release data: ${_GH_RELEASE_DATA}"
-        sh.die.err 42 "release tag ${GH_RELEASE_TAG} does not exists"
+    if echo "${_GH_RELEASE_DATA}" | grep -q '"message": "Not Found"' >/dev/null 2>&1; then
+        msg_debug "release data: ${_GH_RELEASE_DATA}"
+        sh_die_err 42 "release tag ${GH_RELEASE_TAG} does not exists"
     fi
-    if echo "${_GH_RELEASE_DATA}" | grep -q '"message":"API rate limit exceeded' &>/dev/null; then
-        msg.debug "release data: ${_GH_RELEASE_DATA}"
-        sh.die.err 42 "GitHub API rate limit exceeded. Wait or use GH_TOKEN."
+    if echo "${_GH_RELEASE_DATA}" | grep -q '"message":"API rate limit exceeded' >/dev/null 2>&1; then
+        msg_debug "release data: ${_GH_RELEASE_DATA}"
+        sh_die_err 42 "GitHub API rate limit exceeded. Wait or use GH_TOKEN."
     fi
     echo "${_GH_RELEASE_DATA}"
 }
 
-gh.release_tag() {
+gh_release_tag() {
     if [ "${GH_RELEASE_TAG}" = "latest" ]; then
-        GH_RELEASE_TAG="$(gh.latest_release)"
+        GH_RELEASE_TAG="$(gh_latest_release)"
     fi
     echo "${GH_RELEASE_TAG}"
 }
 
-gh.get_release_data() {
+gh_get_release_data() {
     local url
-    url="https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/releases/tags/$(gh.release_tag)"
-    msg.debug "gh.get_release_data() URL ${url}"
+    url="https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/releases/tags/$(gh_release_tag)"
+    msg_debug "gh_get_release_data() URL ${url}"
     curl --silent -L \
         -H "Accept: application/vnd.github+json" \
         -H "X-GitHub-Api-Version: ${GH_API_VERSION}" \
@@ -361,8 +370,8 @@ gh.get_release_data() {
         "${url}"
 }
 
-gh.download_asset() {
-    # usage: gh.download_asset <target file name> <asset id>
+gh_download_asset() {
+    # usage: gh_download_asset <target file name> <asset id>
 
     local fname="${1}"
     local aid="${2}"
@@ -370,18 +379,18 @@ gh.download_asset() {
     local filesize
 
     url="https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/releases/assets/${aid}"
-    msg.debug "gh.download_asset URL ${url}"
+    msg_debug "gh_download_asset URL ${url}"
     curl --silent -L \
         -H "Accept: application/octet-stream" \
         -H "X-GitHub-Api-Version: ${GH_API_VERSION}" \
         -H "${AUTH}" \
-        "${url}" -o "${fname}" || sh.die.err $? "can't download ${url}"
+        "${url}" -o "${fname}" || sh_die_err $? "can't download ${url}"
 
     # check if the response from GH is just a "Not Found"
     filesize=$(wc -c <"${fname}")
     if [ "${filesize}" -ge 30 ]; then
         if head -c 30 "${fname}" | grep -q "Not Found"; then
-            msg.err "Asset Not Found: ${url}"
+            msg_err "Asset Not Found: ${url}"
             return 42
         fi
     fi
@@ -390,58 +399,56 @@ gh.download_asset() {
 # script helpers
 # --------------
 
-msg.err() {
+msg_err() {
     printf "${_BRed}ERROR:${_creset} %s\n" "$*" >&2
     return 0
 }
-msg.warn() {
+msg_warn() {
     printf "${_BBlue}WARN:${_creset}  %s\n" "$*" >&2
     return 0
 }
-msg.info() {
+msg_info() {
     if [ "${VERBOSE}" -ge 1 ]; then
         printf "${_BGreen}INFO:${_creset}  %s\n" "$*" >&2
     fi
     return 0
 }
-msg.debug() {
+msg_debug() {
     if [ "${VERBOSE}" -ge 2 ]; then
         printf "${_BYellow}DEBUG:${_creset} %s\n" "$*" >&2
     fi
     return 0
 }
 
-sh.die.err() {
-    msg.err "(${1-1}) ${2-died} "
+sh_die_err() {
+    msg_err "(${1-1}) ${2-died} "
     exit "${1-1}"
 }
 
-sh.prompt-err() {
-
+sh_prompt_err() {
     ## Use this as last command in your function to prompt an ERROR message if
     ## the exit code is not zero.
-
     local err=${1}
-    [ "${err}" -ne 0 ] && msg.err "${FUNCNAME[1]} exit with error (${err})"
+    [ "${err}" -ne 0 ] && msg_err "${FUNCNAME[1]} exit with error (${err})"
     return "${err}"
 }
 
-sh.in_array() {
+sh_in_array() {
     local word="${1}"
     shift
     for e in "$@"; do [ "${e}" = "${word}" ] && return 0; done
     return 1
 }
 
-sh.count() {
+sh_count() {
     echo $#
 }
 
-scripts.requires() {
+scripts_requires() {
     local exit_val=0
     while [ -n "${1-}" ]; do
-        if ! command -v "${1}" &>/dev/null; then
-            msg.err "missing command ${1}"
+        if ! command -v "${1}" >/dev/null 2>&1; then
+            msg_err "missing command ${1}"
             exit_val=42
         fi
         shift
@@ -452,34 +459,35 @@ scripts.requires() {
 main() {
     local cmd="${1:-help}"
     shift || true
-    scripts.requires "${_REQUIREMENTS[@]}" || sh.die.err $? "first install missing requirements"
+    # shellcheck disable=SC2086 # We actually need word splitting of _REQUIREMENTS here
+    scripts_requires ${_REQUIREMENTS} || sh_die_err $? "first install missing requirements"
 
     if [ -n "${GH_TOKEN}" ]; then
-        msg.debug "Using Github token to avoid rate limits and allow draft downloads"
+        msg_debug "Using Github token to avoid rate limits and allow draft downloads"
         AUTH="Authorization: Bearer ${GH_TOKEN}"
     else
         AUTH="X-noop;"
     fi
 
     if [ "${cmd}" = "help" ] || [ "${cmd}" = "--help" ]; then
-        cmd.help
+        cmd_help
     else
         if [ "${cmd}" = "list" ] || [ "${cmd}" = "install" ]; then
             # Needed to fill 'cache' environment variables:
-            gh.release_data >/dev/null
-            nerd.released_archives >/dev/null
+            gh_release_data >/dev/null
+            nerd_released_archives >/dev/null
         fi
-        _type="$(type -t "cmd.${cmd}")" || true
+        _type="$(type -t "cmd_${cmd}")" || true
         if [ "${_type}" != "function" ]; then
-            sh.die.err 42 "unknown command: ${cmd} / use --help"
+            sh_die_err 42 "unknown command: ${cmd} / use --help"
         fi
 
         if [ "${1-}" = '--help' ]; then
-            _type="$(type -t "cmd.${cmd}.help")" || true
+            _type="$(type -t "cmd_${cmd}_help")" || true
             if [ "${_type}" = 'function' ]; then
-                "cmd.${cmd}.help"
+                "cmd_${cmd}_help"
             else
-                "cmd.help"
+                "cmd_help"
             fi
         else
             [ "${VERBOSE}" -ge 3 ] && set -x
